# Site settings
<<<<<<< HEAD
title: Suwith
email: suwith@kookin.ac.kr
description: > # this means to ignore newlines until "baseurl:"
  I am happy
=======

title: Suwith

email: suwith@kookin.ac.kr

description: > # this means to ignore newlines until "baseurl:"

  I am happy

>>>>>>> 06e201d00772fb1fe15e8df61e0a7fa1293d643e
baseurl: "" # the subpath of your site, e.g. /newpath-for-emping

url: "http://example.com" # the base hostname & protocol for your site
<<<<<<< HEAD
instagram_username: 11.47o9_
github_username:  suwith

=======

instagram_username: 11.47o9_

github_username:  suwith

 

 
>>>>>>> 06e201d00772fb1fe15e8df61e0a7fa1293d643e

sass:

    style: compressed

 

# Build settings

markdown: kramdown

kramdown:

  parse_block_html: true

 

gems:

  - jekyll-redirect-from

  - jekyll-paginate

  - jekyll-sitemap

  - jekyll-seo-tag

  - jekyll-feed

  - jemoji

 

defaults:

    - {scope: {type: posts}, values: {layout: post, permalink: '/blog/:title'}}

 

include:

  - _pages

 

exclude:

  - CNAME

  - README.md

  - Gemfile

  - Gemfile.lock

 

paginate: 12

paginate_path: '/blog/:num'
